### ISSUE TITLE
Use async wait instead of sync wait problem

### ISSUE THREAD

**Issue by NN---** [prodot/ReCommended-Extension#44]
```cs
void F()
{
  DoAsync().Wait();
}
```

After context action `use await` it becomes:

```cs
void F()
{
 await DoAsync().ConfigureAwait(false);
}
```

But then you got another error from ReCommended extension:
`Elide async/await`

Using `Elide async/await` context action the function doesn't restore to original:

```cs
void F()
{
 return DoAsync();
}
```

I understand that ReCommended extensions is strongly opposed to any synchronous wait even if it is desired in the code. Correct ?

**Comment by michael-damatov** [comment]
The `Elide async/await` is not a context action of the _ReCommended extension_.

It has the inspection "Redundant await", but it won't suggest to remove `async/await` in your case because not all required conditions are true (s. [wiki](https://github.com/prodot/ReCommended-Extension/wiki/Redundant-Async-Await)), esp. the type of the awaited expression does not match the return type of the method.

Feel free to reopen the issue if this doesn't answer your question.

**Comment by NN---** [comment]
I guess it is conflict with Roslynator .
I’ll check.

Thanks
